apiVersion: v1
kind: Service
metadata:
  name: {{.Values.application.name}}
  labels:
    run: {{.Values.application.name}}
spec:
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{.Values.application.name}}
  type: LoadBalancer
